services:
  frontend:
    container_name: opinionated-nextjs-starter
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - frontend
    ports: 
      - 3000:3000

networks:
  frontend:
    driver: bridge